### PR TITLE
Update for Gutenberg 16.9

### PR DESCRIPTION
**Pull request by johngodley**
The plugin now only works with specific versions of Gutenberg. This sets it at 16.9

### CODE REVIEW

**Comment by akirk** [comment]
Could you elaborate on this new requirement? Does it still work with the block editor as shipped with WordPress? Is there a chance to merge the Gutenberg-dependent blocks everywhere functionality into Gutenberg and just keep opt-in part in the plugin?

**Comment by johngodley** [comment]
> Does it still work with the block editor as shipped with WordPress

No, it will only work with the version of Gutenberg specified (16.9)

> Is there a chance to merge the Gutenberg-dependent blocks everywhere functionality into Gutenberg and just keep opt-in part in the plugin?

Not sure what you mean here?

**Comment by akirk** [comment]
So I've been bundling blocks-everywhere in the Friends plugin (see https://github.com/akirk/friends/issues/264) and I cannot see how this change can let me continue to use it there since typically people would have WordPress without Gutenberg. Thus I was thinking if the break-on-non-latest-Gutenberg-version part could be actually part of Gutenberg this would solve this.

**Comment by johngodley** [comment]
I would very much like not to be making this change as it makes life very difficult for everyone. However, changes in Gutenberg have forced it. I would suggest bundling whichever version of the plugin is compatible with your plugin and sticking with that. However at some point the version bundled with WordPress will no longer work (I'm surprised it still does). My hope is that a better solution will be found before then.

> if the break-on-non-latest-Gutenberg-version part could be actually part of Gutenberg this would solve this

Possibly there are different ways of resolving things better but I'm not working on it right now and it's unlikely to change soon. The change here is the minimum needed to get it working on wordpress.com and wordpress.org where things broke after trying to update.

**Comment by akirk** [comment]
I understood the motivation, of course! Just sharing the perspective from someone who doesn't control the plugin environment :-) And trying to think of a way that might be more robust in future.

So for the moment, I understand it'd work best to just remove it in my usecase. Thanks for your work!

**Pull request merged**
